name: CICD de la mort qui tue
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build
    runs-on: ubuntu-latest
    steps:
      - run: git pull
      - run: echo "🎉 Lancement du dockerFile 💀"
      - run: docker build -t europe-west9-docker.pkg.dev/sandbox-444912/student-matthieu/${{ github.event.head_commit.message }} .
      - run: echo "🐧 Push de l'image dans le registery 🧌"
      - run: docker push europe-west9-docker.pkg.dev/sandbox-444912/student-matthieu/${{ github.event.head_commit.message }}
      - run: echo "Deploy de l'image sur GCLOUD 🔫 !
      - run: gcloud run deploy service-student-matthieu-preprod --region=europe-west9 --image=europe-west9-docker.pkg.dev/sandbox-444912/student-matthieu/${{ github.event.head_commit.message }}
      - run: echo "🖥️ Tada c'est fini 🥇"
